#!/usr/bin/expect -f

log_user 0

send_user "Root's password: "
stty -echo
expect_user -re "(.*)\n"
stty echo
set password $expect_out(1,string)

spawn -ignore HUP su
expect "Password: "
send "$password\n"
expect "$"

send_user "\n\nCompiling... "

send "pkill -9 bessd\n"
expect
send "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig ./build.py bess\n"
expect

send_user "Done.\n"
